import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { NavBar } from '@/components/NavBar/NavBar'
import { Footer } from '@/components/Footer/Footer'
import { notFound } from 'next/navigation'
import { NextIntlClientProvider, useMessages } from 'next-intl'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const locales = ['en', 'pt'];

export default async function RootLayout({
  children, params: {locale}
}: {
  children: React.ReactNode,
  params: {locale: string}
}) {
  if (!locales.includes(locale as any)) notFound();

  let messages;
  try{
    messages = (await import(`../../../messages/${locale}.json`)).default;
  }catch(e){
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale= {locale} messages= {messages}>
          <NavBar />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
